Linux build fixes2 (#445)
* fix pro - remove windows paths and add missing sources

* Fix undefined reference to __real_dlopen on Linux build

Including dlopen_wrapper.c leaves an undefined reference at link time.

dlopen_wrapper.c:(.text+0x54): undefined reference to `__real_dlopen'

Removing dlopen_wrapper.c allowd the build to complete successfully.

This was added by commit 7b0e2b2. It doesn't appear to be needed for
Linux but I am not sure about other unix-likes (such as macOS).